workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  image: node:lts-alpine
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm i -D
    - npm run build-docs
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
